"""Initial schema: trades table with 5 modules

Revision ID: 06a3e73b27f7
Revises: 
Create Date: 2026-02-27 11:10:57.814946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a3e73b27f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键，UUID v4'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户标识'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间 (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间 (UTC)'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='软删除标记时间'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观锁版本号'),
    sa.Column('llm_analysis_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='llm_analysis_status_enum'), nullable=False, comment='LLM 分析状态'),
    sa.Column('llm_raw_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='LLM 原始返回日志 (JSON)'),
    sa.Column('account_type', sa.Enum('SHORT_TERM', 'MEDIUM_TERM', name='account_type_enum'), nullable=False, comment='交易账户类型 (短线/中线)'),
    sa.Column('stock_code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('trade_cycle', sa.Enum('SHORT_TERM', 'MEDIUM_TERM', 'LONG_TERM', name='trade_cycle_enum'), nullable=False, comment='交易周期'),
    sa.Column('entry_date', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='买入时间'),
    sa.Column('exit_date', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='卖出时间'),
    sa.Column('position_size', sa.Float(), nullable=False, comment='持仓仓位占比 (%)'),
    sa.Column('entry_price', sa.Float(), nullable=False, comment='实际买入均价'),
    sa.Column('exit_price', sa.Float(), nullable=True, comment='实际卖出均价'),
    sa.Column('preset_stop_loss', sa.Float(), nullable=True, comment='预设止损价'),
    sa.Column('preset_take_profit', sa.Float(), nullable=True, comment='预设止盈价'),
    sa.Column('slippage', sa.Float(), nullable=True, comment='滑点/交易损耗'),
    sa.Column('max_favorable_excursion', sa.Float(), nullable=True, comment='最大浮盈 (MFE)'),
    sa.Column('max_adverse_excursion', sa.Float(), nullable=True, comment='最大浮亏 (MAE)'),
    sa.Column('pnl_amount', sa.Float(), nullable=True, comment='实际盈亏金额'),
    sa.Column('pnl_ratio', sa.Float(), nullable=True, comment='实际盈亏比例 (%)'),
    sa.Column('pnl_flag', sa.Enum('PROFIT', 'LOSS', 'BREAKEVEN', name='pnl_flag_enum'), nullable=True, comment='盈亏标识'),
    sa.Column('market_environment', sa.Enum('BULL_MAIN_RISE', 'BULL_CORRECTION', 'BEAR_MAIN_FALL', 'BEAR_REBOUND', 'RANGE_UPPER', 'RANGE_LOWER', 'RANGE_MIDDLE', name='market_environment_enum'), nullable=True, comment='市场环境'),
    sa.Column('sector_status', sa.Enum('STARTUP', 'MAIN_RISE', 'CLIMAX', 'RETREAT', 'CHAOS', name='sector_status_enum'), nullable=True, comment='板块阶段'),
    sa.Column('selection_dimension', postgresql.ARRAY(sa.String()), nullable=True, comment='选股维度 (技术面/政策面/基本面/事件驱动/情绪接力)'),
    sa.Column('strategy_pattern', postgresql.ARRAY(sa.String()), nullable=True, comment='买入模式标签 (突破买入/回踩低吸/龙头首阴等)'),
    sa.Column('volume_profile', sa.String(length=500), nullable=True, comment='量能特征'),
    sa.Column('thesis_statement', sa.Text(), nullable=True, comment='买入论点 — LLM 语义分析核心依据'),
    sa.Column('plan_adherence', sa.Enum('FULL_COMPLIANCE', 'SLIGHT_DEVIATION', 'IMPULSIVE', name='plan_adherence_enum'), nullable=True, comment='计划执行度'),
    sa.Column('stop_loss_discipline', sa.Enum('PRESET_AND_EXECUTED', 'PRESET_NOT_EXECUTED', 'NO_PRESET', name='stop_loss_discipline_enum'), nullable=True, comment='止损纪律'),
    sa.Column('exit_type', sa.Enum('ACTIVE_PROFIT', 'PASSIVE_STOP', 'BREAKEVEN_EXIT', 'EMOTIONAL_EXIT', name='exit_type_enum'), nullable=True, comment='离场类型'),
    sa.Column('exit_reason', sa.Text(), nullable=True, comment='具体卖出理由'),
    sa.Column('psychological_state', sa.Enum('CALM', 'FOMO', 'GREED', 'FEAR', name='psychological_state_enum'), nullable=True, comment='交易时心理状态'),
    sa.Column('result_type', sa.Enum('CORRECT_PROFIT', 'LUCKY_PROFIT', 'EXECUTION_LOSS', 'PATTERN_LOSS', name='result_type_enum'), nullable=True, comment='结果类型 (正确盈利/运气盈利/执行亏损/模式亏损)'),
    sa.Column('error_level', sa.Enum('EXECUTION_ERROR', 'PATTERN_ERROR', 'ENVIRONMENT_ERROR', name='error_level_enum'), nullable=True, comment='错误层级'),
    sa.Column('environment_mismatch_flag', sa.Boolean(), nullable=True, comment='环境错配标记'),
    sa.Column('permanent_exclusion_flag', sa.Boolean(), nullable=True, comment='永久排除标记 (绝对错误行为)'),
    sa.Column('correct_action', sa.Text(), nullable=False, comment='对应的正确行为 (必填)'),
    sa.Column('llm_action_item', sa.Text(), nullable=True, comment='LLM 生成的行动指令'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_user_deleted', 'trades', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_trades_entry_date'), 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_market_environment'), 'trades', ['market_environment'], unique=False)
    op.create_index(op.f('ix_trades_result_type'), 'trades', ['result_type'], unique=False)
    op.create_index(op.f('ix_trades_stock_code'), 'trades', ['stock_code'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_stock_code'), table_name='trades')
    op.drop_index(op.f('ix_trades_result_type'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_environment'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_date'), table_name='trades')
    op.drop_index('idx_trades_user_deleted', table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
