"""add base_capital to users

Revision ID: d5e39cdc6f9a
Revises: c47f3112f059
Create Date: 2026-03-03 16:03:36.999192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e39cdc6f9a'
down_revision: Union[str, None] = 'c47f3112f059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('base_capital', sa.Float(), server_default='100000', nullable=False, comment='模拟总资金'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_capital')
    # ### end Alembic commands ###
